CREATE TABLE [dbo].[Person]
(
	[UserId] NVARCHAR(128) NOT NULL,
	[DateOfBirth] DATETIME NOT NULL,
	[Gender] VARCHAR(10) NOT NULL,
	[AddressLine1] VARCHAR(250) NOT NULL,
	[AddressLine2] VARCHAR(250) NULL,
	[City] VARCHAR(100) NOT NULL

	CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED ([UserId]),
	CONSTRAINT [FK_Person_AspNetUsers] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers]([Id])
)
